# Generated by Django 4.2.2 on 2023-06-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
